### ISSUE TITLE
Blaze/Handlebars vs Edge

### ISSUE THREAD

**Issue by harryadel** [edge-js/edge#147]
### Package version

6.0

### Describe the bug

Given your knowledge of edge, how feasible do you think it's to make it backwards compatible with [Blaze](https://github.com/meteor/blaze)? I already started a discussion about this on the [forums](https://forums.meteor.com/t/blaze-handlebars-vs-edge/60976) and [GH](https://github.com/meteor/blaze/discussions/442). 

In terms of the syntax, it's pretty similar, though the issue lies in the other sematics that're found in the js file accompanying the html file like [helpers](https://www.blazejs.org/api/templates#Template-helpers) and [events](https://www.blazejs.org/api/templates#Template-events). Also, lifecycle events  like [onRendered](https://www.blazejs.org/api/templates#Template-onRendered), [onCreated](https://www.blazejs.org/api/templates#Template-onCreated) and [onDestroyed](https://www.blazejs.org/api/templates#Template-onDestroyed).

This has pretty big upsides to both parties. For edge, this would open up the gates to lots of Meteor developers and the associated community. And for us Meteor developers, this means a much modern view layer that's actually well maintained.

On a side note, I do believe both Meteor & Adonis are tying to achieve the same thing yet go different about it due to their heritage and circumstances. It'd be definitely great to merge our efforts and learn from each other.   

Looking forward to hearing your opinion on this @thetutlage

**Comment by thetutlage** [comment]
Hello @harryadel 

Sorry it took a while to reply to this thread, as I was busy with other work.

I am not much aware with the inner workings of Blaze. At the high level, it looks like a template engine that renders on the backend and then provide reactivity on the frontend at the same time.

I am personally not a big fan of blurring lines when it comes to templating. I use Edge to render static HTML and then use Alpine.js separately for interactivity. 

So for now, I will let Edge as it is and not change its direction. 

Also, I read this discussion thread https://github.com/meteor/blaze/discussions/442 and I agree with radekmie, mixing Blaze and Edge is impossible because of different ideas and the different directions
