### ISSUE TITLE
If a variable passed to view is 0 (int), the "echo" will be empty

### ISSUE THREAD

**Issue by danilopolani** [edge-js/edge#25]
In my controller, I pass variables to my view like this:

```
return view.render('search', {
  total: 0
})
```

From my view, if I do `{{ total }}` it will be empty, but it works if I pass the variable like a string:

```
return view.render('search', {
  total: '0'
})
```

**Comment by anhnt** [comment]
got the same bug

**Comment by adamlc** [comment]
@RomainLanz any updates on this? I noticed it doesn't seem to be working in 1.1.4 either

**Comment by richie3366** [comment]
Since we were not sure if the new version of edge (which fixed the issue) was ready to use for us, we made a quick fix on a fork repo (https://github.com/Pickaw/edge) that you can also fork to use it on your project.

With Yarn, you can specify a peer resolution by adding this property in your `package.json` file:
```
  "resolutions": {
    "**/edge.js": "Pickaw/edge"
  },
```

**WARN:** I recommend to fork our repo and use "githubUsername/edge" in your resolutions property, since we could delete our repo at any time when we won't need it anymore.
